<?php
    use \Jobeet\Filter\Slugify as Slugify;

    $slug = new Slugify();
?>
<table class="jobs">
    <tbody>
        <?php foreach($this->jobs as $test => $job): ?>
            <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
                <td class="location"><?php echo $this->escapeHtml($job->location); ?></td>
                <td class="position">
                    <a href="<?php echo $this->url('get_job',
                        array(
                            'company' => $slug->filter($job->company),
                            'position' => $slug->filter($job->position),
                            'location' => $slug->filter($job->location),
                            'id'     => $job->id_job
                        ), false, false);?>">
                        <?php echo $this->escapeHtml($job->position); ?>
                    </a>
                </td>
                <td class="company">
                    <?php echo $this->escapeHtml($job->company); ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
