<?php
	Jobeet::slugify($text);

    $this->headLink()->appendStylesheet('/css/jobs.css');
?>
<h1><?php echo $this->escapeHtml($this->category->name); ?></h1>
<table class="jobs">
    <tbody>
        <?php foreach($this->jobs as $job): ?>
        <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
            <td class="location"><?php echo $this->escapeHtml($job->location); ?></td>
            <td class="position">
                <a href="<?php echo $this->url('job',
                		array(
							'company' => Jobeet::slugify($job->c),
							'position' => Jobeet::slugify($job->position),
							'location' => Jobeet::slugify($job->location),
							'id'     => '[0-9]+',
							'action'=>'get',
							'id'=>$job->idJob));?>">
                
                    <?php echo $this->escapeHtml($job->position); ?>
                </a>
            </td>
            <td class="company">
                <?php echo $this->escapeHtml($job->company); ?>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
