<?php
    $container = $this->navigation()->breadcrumbs();
?>
    <ul class="breadcrumb">
        <li><?php echo $this->translate("You are here");?> :</li>
        <?php foreach($this->pages as $page): ?>
            <?php if( ! $page->isActive()): ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a>
                    <span class="divider"> &gt; </span>
                </li>
            <?php else: ?>
                <li class="active">
                    <?php if($container->getLinkLast()): ?>
                        <a href="<?php echo $page->getHref() ?>">
                    <?php endif ?>
                    <?php echo $page->getLabel() ?>
                    <?php if($container->getLinkLast()): ?>
                        </a>
                    <?php endif ?>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
