<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcadmin/login'));
$form->setAttribute('method', 'post');
// $form->setAttribute('class', 'form-horizontal');
?>
<div class="row">
    <div class="span4 offset4">
        <?php echo $this->form()->openTag($form);?>
            <fieldset>
            <legend class="legend">
                <i class="fam-key"></i> Login
            </legend>
            <div class="control-group">
                    <?php echo $this->formElementErrors($form->get('identity'))?>
                    <?php echo $this->formLabel($form->get('identity')->setAttribute('class', 'control-label')); ?>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('identity')->setAttribute('class', 'input-xlarge')->setAttribute('id', 'identity')); ?>
                    </div>
            </div>

            <div class="control-group">
                    <?php echo $this->formElementErrors($form->get('credential'))?>
                    <?php echo $this->formLabel($form->get('credential')->setAttribute('class', 'control-label')); ?>
                    <div class="controls">
                        <?php echo $this->formInput($form->get('credential')->setAttribute('class', 'input-xlarge')->setAttribute('id', 'credential')); ?>
                    </div>
            </div>

            <div class="control-group">
                <div class="controls">
                        <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-success')); ?>
                    </div>
                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect"
                    value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
                </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
