<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/main.css');
        ?>
        <title>ZF2 - Jobeet</title>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div class="content">
                    <h1>
                        <a href="<?php echo $this->url('home');?>">
                            <img src="/images/logo.jpg" alt="Jobeet Job Board" />
                        </a>
                    </h1>
                    <div id="sub_header">
                        <div class="post">
                            <h2>Ask for people</h2>
                            <div>
                                <a href="#">Post a Job</a>
                            </div>
                        </div>
                        <div class="search">
                            <h2>Ask for a job</h2>
                            <form action="#" method="get">
                                <input type="text" name="keywords" id="search_keywords" />
                                <input type="submit" value="search" />
                                <div class="help">Enter some keywords (city, country, position, ...)</div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="content">
                <div class="content">
                    <div id="job_history">Recent viewed jobs:<?php echo $this->jobSessions(); ?></div>
                    <?php echo $this->content; ?>
                </div>
            </div>
            <div id="footer">
                <div class="content">
                    <span class="symfony">
                        <img src="/images/jobeet-mini.png" alt="logo jobeet" /> powered by <a href=""><img src="/images/zf2-logo.png" alt="Zend Framework 2" /></a>
                    </span>
                    <ul>
                        <li><a href="">About Jobeet</a></li>
                        <li class="feed"><a href="">Full feed</a></li>
                        <li><a href="">Jobeet API</a></li>
                        <li class="last"><a href="">Affiliates</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>
