<?php
    $this->headLink()->appendStylesheet('/css/jobs.css');
?>
<h1><?php echo $this->escapeHtml($this->category->name); ?></h1>
<?php echo $this->partial('/partials/job_list.phtml', array('jobs' => $this->jobs));?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml', (
        array(
            'id' => $this->id,
            'slug' => $this->category->slug
        )
    )
); ?>
