<?php
    $this->headLink()->appendStylesheet('/css/jobs.css');
?>
<?php foreach ($this->results as $result): ?>
    <div class="category">
        <div class="feed">
          <a href="">Feed</a>
        </div>
        <h1>
            <a href="<?php echo $this->url('list_category_page', array('slug' => $result['category']->slug))?>">
                <?php echo $result['category']->name; ?>
            </a>
        </h1>
    </div>
    
    <?php
        // On appelle ici notre vue Partiel, on lui passe les jobs en paramètre
        echo $this->partial('/partials/job_list', array('jobs' => $result['job']));
    ?>

    <?php if (($count = (int)$result['activeJobs'] - $this->nbJobByCategory) > 0): ?>
        <div class="more_jobs">
          et <a href="<?php echo $this->url('list_category_page', array('slug' => $result['category']->slug))?>">
                <?php echo $count;?>
            </a> autres...
        </div>
    <?php endif; ?>
<?php endforeach;?>
