<?php
    $this->headLink()->appendStylesheet('/css/jobs.css');
?>
<?php foreach ($this->results as $result): ?>
    <div class="category">
        <div class="feed">
          <a href="">Feed</a>
        </div>
        <h1><a href="<?php echo $this->url('category', array('action' => 'list', 'id' => $result['category']->idCategory))?>"><?php echo $result['category']->name; ?></a></h1>
    </div>
    <table class="jobs">
        <tbody>
            <?php foreach($result['job'] as $job): ?>
                <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
                    <td class="location"><?php echo $this->escapeHtml($job->location); ?></td>
                    <td class="position">
                        <a href="<?php echo $this->url('job', array('action'=>'get', 'id'=>$job->idJob));?>">
                            <?php echo $this->escapeHtml($job->position); ?>
                        </a>
                    </td>
                    <td class="company">
                        <?php echo $this->escapeHtml($job->company); ?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php endforeach;?>
