<div class="container">
    <a href="<?php echo $this->url('zfcadmin/category/action', array('action' => 'add'), null, false);?>">
        <i class="fam-add"></i><?php echo $this->translate("New Category");?>
    </a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate("Category");?></th>
                <th>Slug</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->categories as $category):?>
                <tr>
                    <td><?php echo $category->id_category; ?></td>
                    <td><?php echo $category->name; ?></td>
                    <td><?php echo $category->slug; ?></td>
                    <td>
                        <?php
                            $urlEdit = $this->url('zfcadmin/category/action',array('action' => 'edit', 'id' => $category->id_category), null, false);
                            $urlDelete = $this->url('zfcadmin/category/action', array('action' => 'delete', 'id' => $category->id_category), null, false);
                        ?>
                        <a href="<?php echo $urlEdit;?>"><i class="fam-pencil"></i></a>
                        <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?>
</div>
