<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/category');?>"><i class="fam-cog"></i> Categories</a>
        </div>
        <div class="span9">
            Categories management
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/job');?>"><i class="fam-page"></i> Jobs</a>
        </div>
        <div class="span9">
            Jobs management
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-user"></i> Users</a>
        </div>
        <div class="span9">
            Users management
        </div>
    </div>
</div>
