<div class="container">
    <h2><?php echo $this->translate("Homepage");?></h2>
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/category');?>"><i class="fam-cog"></i> <?php echo $this->translate("Categories");?></a>
        </div>
        <div class="span9">
            <?php echo $this->translate("Categories management");?>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/job');?>"><i class="fam-page"></i> <?php echo $this->translate("Jobs");?></a>
        </div>
        <div class="span9">
            <?php echo $this->translate("Jobs management");?>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-user"></i> <?php echo $this->translate("Users");?></a>
        </div>
        <div class="span9">
            <?php echo $this->translate("Users management");?>
        </div>
    </div>
</div>
