<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/category');?>"><i class="fam-cog"></i> Catégories</a>
        </div>
        <div class="span9">
            Gestion des catégories
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="<?php echo $this->url('zfcadmin/job');?>"><i class="fam-page"></i> Jobs</a>
        </div>
        <div class="span9">
            Gestion des emplois
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-user"></i> Utilisateurs</a>
        </div>
        <div class="span9">
            Gestion des utilisateurs
        </div>
    </div>
</div>
