<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate("Category");?></th>
                <th><?php echo $this->translate("Type");?></th>
                <th><?php echo $this->translate("Company");?></th>
                <th><?php echo $this->translate("Location");?></th>
                <th><?php echo $this->translate("Public");?></th>
                <th><?php echo $this->translate("Activated");?></th>
                <th><?php echo $this->translate("Actions");?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->jobs as $job):?>
                <tr>
                    <td><?php echo $job->id_job;?></td>
                    <td><?php echo $job->id_category;?></td>
                    <td><?php echo $job->type;?></td>
                    <td><?php echo $job->company;?></td>
                    <td><?php echo $job->location;?></td>
                    <td><?php echo ($job->is_public) ? $this->translate('Yes') : $this->translate('No');?></td>
                    <td><?php echo ($job->is_activated) ? $this->translate('Yes') : $this->translate('No');?></td>
                    <td>
                        <?php
                            $urlEdit = $this->url('zfcadmin/job/action',array('action' => 'edit', 'id' => $job->id_job), null, false);
                            $urlDelete = $this->url('zfcadmin/job/action', array('action' => 'delete', 'id' => $job->id_job), null, false);
                        ?>
                        <a href="<?php echo $urlEdit;?>"><i class="fam-pencil"></i></a>
                        <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?>
</div>
